names = []
names.append('Joe')
names.append('Sally')
names.append('Jim')
names.append('June')
names.append('Betty')
names.append('Bill')
names.append('Sara')
names.append('Zak')
names.append('Anne')
names.append('Kate')
print ("Queues are First-In First-Out (FIFO) data structures") 
print("\nInitial queue. Used names.append(item) to enter elements into the queue")
print (names)
print("\nElements dequeued from queue. Used names.pop(0) to pop element in front") 
print(names.pop(0)) 
print(names.pop(0))
print(names.pop(0)) 
print(names.pop(0))
print(names.pop(0)) 
print(names.pop(0))
print(names.pop(0)) 
print(names.pop(0))
print(names.pop(0)) 
print(names.pop(0))
print(names)


